// <auto-generated />
using System;
using FreelanceHub.Infrastructure.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FreelanceHub.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260720024022_AddRoleSpecificRegistration")]
    partial class AddRoleSpecificRegistration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FreelanceHub.Domain.Models.Application", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("application_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicationId"));

                    b.Property<int>("ApplicationStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(50)
                        .HasColumnName("application_status");

                    b.Property<string>("CoverLetter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cover_letter");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("FreelancerUserId")
                        .HasColumnType("int")
                        .HasColumnName("freelancer_user_id");

                    b.Property<int>("JobId")
                        .HasColumnType("int")
                        .HasColumnName("job_id");

                    b.Property<decimal>("ProposedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("proposed_amount");

                    b.Property<int>("TimelineDays")
                        .HasColumnType("int")
                        .HasColumnName("timeline_days");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("ApplicationId");

                    b.HasIndex("FreelancerUserId");

                    b.HasIndex("JobId");

                    b.ToTable("applications", null, t =>
                        {
                            t.HasCheckConstraint("chk_applications_status", "[application_status] IN (50, 51, 52, 53, 54)");
                        });
                });

            modelBuilder.Entity("FreelanceHub.Domain.Models.ApplicationAttachment", b =>
                {
                    b.Property<int>("ApplicationId")
                        .HasColumnType("int")
                        .HasColumnName("application_id");

                    b.Property<int>("AttachmentId")
                        .HasColumnType("int")
                        .HasColumnName("attachment_id");

                    b.HasKey("ApplicationId", "AttachmentId");

                    b.HasIndex("AttachmentId");

                    b.ToTable("application_attachments", (string)null);
                });

            modelBuilder.Entity("FreelanceHub.Domain.Models.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("is_email_verified");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("last_name");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("normalized_username");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int?>("ProfileImageAttachmentId")
                        .HasColumnType("int")
                        .HasColumnName("profile_image_attachment_id");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("username");

                    b.Property<int>("UserStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(10)
                        .HasColumnName("user_status");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("EmailIndex")
                        .HasFilter("[normalized_email] IS NOT NULL");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[normalized_username] IS NOT NULL");

                    b.HasIndex("ProfileImageAttachmentId");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("chk_users_status", "[user_status] IN (10, 11, 12, 13)");
                        });
                });

            modelBuilder.Entity("FreelanceHub.Domain.Models.ApplicationUserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("assigned_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("FreelanceHub.Domain.Models.Attachment", b =>
                {
                    b.Property<int>("AttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("attachment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttachmentId"));

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("content_type");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("file_url");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("original_file_name");

                    b.Property<string>("StoredFileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("stored_file_name");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("uploaded_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("UploadedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("uploaded_by_user_id");

                    b.HasKey("AttachmentId");

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("attachments", null, t =>
                        {
                            t.HasCheckConstraint("chk_attachments_file_size", "[file_size] IS NULL OR [file_size] >= 0");
                        });
                });

            modelBuilder.Entity("FreelanceHub.Domain.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("CategoryId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("categories", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Web Development"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Mobile Development"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "UI / UX Design"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Writing"
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "Marketing"
                        });
                });

            modelBuilder.Entity("FreelanceHub.Domain.Models.ClientProfile", b =>
                {
                    b.Property<int>("ClientProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("client_profile_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientProfileId"));

                    b.Property<int>("ClientType")
                        .HasColumnType("int")
                        .HasColumnName("client_type");

                    b.Property<string>("CompanyDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("company_description");

                    b.Property<int?>("CompanyLogoAttachmentId")
                        .HasColumnType("int")
                        .HasColumnName("company_logo_attachment_id");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("company_name");

                    b.Property<string>("CompanyWebsite")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("company_website");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("RatingAverage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("rating_averge");

                    b.Property<int>("RatingCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("rating_count");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("ClientProfileId");

                    b.HasIndex("CompanyLogoAttachmentId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("client_profiles", null, t =>
                        {
                            t.HasCheckConstraint("chk_client_profiles_company_details", "[client_type] = 70 OR ([client_type] = 71 AND NULLIF(LTRIM(RTRIM([company_name])), '') IS NOT NULL AND NULLIF(LTRIM(RTRIM([company_description])), '') IS NOT NULL)");

                            t.HasCheckConstraint("chk_client_profiles_type", "[client_type] IN (70, 71)");
                        });
                });

            modelBuilder.Entity("FreelanceHub.Domain.Models.ClientProfileAttachment", b =>
                {
                    b.Property<int>("ClientProfileId")
                        .HasColumnType("int")
                        .HasColumnName("client_profile_id");

                    b.Property<int>("AttachmentId")
                        .HasColumnType("int")
                        .HasColumnName("attachment_id");

                    b.Property<string>("AttachmentType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("attachment_type");

                    b.HasKey("ClientProfileId", "AttachmentId");

                    b.HasIndex("AttachmentId");

                    b.ToTable("client_profile_attachments", (string)null);
                });

            modelBuilder.Entity("FreelanceHub.Domain.Models.Contract", b =>
                {
                    b.Property<int>("ContractId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("contract_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContractId"));

                    b.Property<int>("AcceptedApplicationId")
                        .HasColumnType("int")
                        .HasColumnName("accepted_application_id");

                    b.Property<DateTime?>("ActualCompletionDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("actual_completion_date");

                    b.Property<decimal>("AgreedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("agreed_amount");

                    b.Property<int>("ContractStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(60)
                        .HasColumnName("contract_status");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("ExpectedCompletionDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("expected_completion_date");

                    b.Property<int>("JobId")
                        .HasColumnType("int")
                        .HasColumnName("job_id");

                    b.Property<DateTime>("StartDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("start_date")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("ContractId");

                    b.HasIndex("JobId")
                        .IsUnique();

                    b.HasIndex("AcceptedApplicationId", "JobId")
                        .IsUnique();

                    b.ToTable("contracts", null, t =>
                        {
                            t.HasCheckConstraint("chk_contracts_actual_completion", "[actual_completion_date] IS NULL OR [actual_completion_date] >= [start_date]");

                            t.HasCheckConstraint("chk_contracts_agreed_amount", "[agreed_amount] >= 0");

                            t.HasCheckConstraint("chk_contracts_expected_completion", "[expected_completion_date] IS NULL OR [expected_completion_date] >= [start_date]");

                            t.HasCheckConstraint("chk_contracts_status", "[contract_status] IN (60, 61, 62, 63, 64)");
                        });
                });

            modelBuilder.Entity("FreelanceHub.Domain.Models.ContractAttachment", b =>
                {
                    b.Property<int>("ContractId")
                        .HasColumnType("int")
                        .HasColumnName("contract_id");

                    b.Property<int>("AttachmentId")
                        .HasColumnType("int")
                        .HasColumnName("attachment_id");

                    b.HasKey("ContractId", "AttachmentId");

                    b.HasIndex("AttachmentId");

                    b.ToTable("contract_attachments", (string)null);
                });

            modelBuilder.Entity("FreelanceHub.Domain.Models.FreelancerProfile", b =>
                {
                    b.Property<int>("FreelancerProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("freelancer_profile_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FreelancerProfileId"));

                    b.Property<int>("AvailabilityStatus")
                        .HasColumnType("int")
                        .HasColumnName("availability_status");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("bio");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("ExperienceLevel")
                        .HasColumnType("int")
                        .HasColumnName("experience_level");

                    b.Property<string>("ExternalPortfolioUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("external_portfolio_url");

                    b.Property<decimal>("HourlyRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("hourly_rate");

                    b.Property<string>("ProfessionalTitle")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("professional_title");

                    b.Property<int>("RatingAverage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("rating_averge");

                    b.Property<int>("RatingCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("rating_count");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("FreelancerProfileId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("freelancer_profiles", null, t =>
                        {
                            t.HasCheckConstraint("chk_freelancer_profiles_availability_status", "[availability_status] IN (20, 21, 22)");

                            t.HasCheckConstraint("chk_freelancer_profiles_experience_level", "[experience_level] IN (30, 31, 32)");

                            t.HasCheckConstraint("chk_freelancer_profiles_hourly_rate", "[hourly_rate] > 0");

                            t.HasCheckConstraint("chk_freelancer_profiles_required_details", "NULLIF(LTRIM(RTRIM([professional_title])), '') IS NOT NULL AND LEN(LTRIM(RTRIM([bio]))) >= 20");
                        });
                });

            modelBuilder.Entity("FreelanceHub.Domain.Models.FreelancerProfileAttachment", b =>
                {
                    b.Property<int>("FreelancerProfileId")
                        .HasColumnType("int")
                        .HasColumnName("freelancer_profile_id");

                    b.Property<int>("AttachmentId")
                        .HasColumnType("int")
                        .HasColumnName("attachment_id");

                    b.Property<string>("AttachmentDescription")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("attachment_description");

                    b.HasKey("FreelancerProfileId", "AttachmentId");

                    b.HasIndex("AttachmentId");

                    b.ToTable("freelancer_profile_attachments", (string)null);
                });

            modelBuilder.Entity("FreelanceHub.Domain.Models.FreelancerSkill", b =>
                {
                    b.Property<int>("FreelancerProfileId")
                        .HasColumnType("int")
                        .HasColumnName("freelancer_profile_id");

                    b.Property<int>("SkillId")
                        .HasColumnType("int")
                        .HasColumnName("skill_id");

                    b.HasKey("FreelancerProfileId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("freelancer_skills", (string)null);
                });

            modelBuilder.Entity("FreelanceHub.Domain.Models.Job", b =>
                {
                    b.Property<int>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("job_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobId"));

                    b.Property<decimal>("Budget")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("budget");

                    b.Property<int>("ClientUserId")
                        .HasColumnType("int")
                        .HasColumnName("client_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2")
                        .HasColumnName("deadline");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<int>("JobStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(40)
                        .HasColumnName("job_status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("JobId");

                    b.HasIndex("ClientUserId");

                    b.ToTable("jobs", null, t =>
                        {
                            t.HasCheckConstraint("chk_jobs_budget", "[budget] >= 0");

                            t.HasCheckConstraint("chk_jobs_deleted_at", "([is_deleted] = 0 AND [deleted_at] IS NULL) OR ([is_deleted] = 1 AND [deleted_at] IS NOT NULL)");

                            t.HasCheckConstraint("chk_jobs_status", "[job_status] IN (40, 41, 42, 43)");
                        });
                });

            modelBuilder.Entity("FreelanceHub.Domain.Models.JobAttachment", b =>
                {
                    b.Property<int>("JobId")
                        .HasColumnType("int")
                        .HasColumnName("job_id");

                    b.Property<int>("AttachmentId")
                        .HasColumnType("int")
                        .HasColumnName("attachment_id");

                    b.HasKey("JobId", "AttachmentId");

                    b.HasIndex("AttachmentId");

                    b.ToTable("job_attachments", (string)null);
                });

            modelBuilder.Entity("FreelanceHub.Domain.Models.JobCategory", b =>
                {
                    b.Property<int>("JobId")
                        .HasColumnType("int")
                        .HasColumnName("job_id");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.HasKey("JobId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("job_categories", (string)null);
                });

            modelBuilder.Entity("FreelanceHub.Domain.Models.JobSkill", b =>
                {
                    b.Property<int>("JobId")
                        .HasColumnType("int")
                        .HasColumnName("job_id");

                    b.Property<int>("SkillId")
                        .HasColumnType("int")
                        .HasColumnName("skill_id");

                    b.HasKey("JobId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("job_skills", (string)null);
                });

            modelBuilder.Entity("FreelanceHub.Domain.Models.JobTag", b =>
                {
                    b.Property<int>("JobId")
                        .HasColumnType("int")
                        .HasColumnName("job_id");

                    b.Property<int>("TagId")
                        .HasColumnType("int")
                        .HasColumnName("tag_id");

                    b.HasKey("JobId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("job_tags", (string)null);
                });

            modelBuilder.Entity("FreelanceHub.Domain.Models.Skill", b =>
                {
                    b.Property<int>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("skill_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("SkillId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("skills", (string)null);

                    b.HasData(
                        new
                        {
                            SkillId = 1,
                            Name = "JavaScript"
                        },
                        new
                        {
                            SkillId = 2,
                            Name = "TypeScript"
                        },
                        new
                        {
                            SkillId = 3,
                            Name = "React"
                        },
                        new
                        {
                            SkillId = 4,
                            Name = "Angular"
                        },
                        new
                        {
                            SkillId = 5,
                            Name = "Vue.js"
                        },
                        new
                        {
                            SkillId = 6,
                            Name = "Node.js"
                        },
                        new
                        {
                            SkillId = 7,
                            Name = "ASP.NET Core"
                        },
                        new
                        {
                            SkillId = 8,
                            Name = "PHP"
                        },
                        new
                        {
                            SkillId = 9,
                            Name = "Laravel"
                        },
                        new
                        {
                            SkillId = 10,
                            Name = "Python"
                        },
                        new
                        {
                            SkillId = 11,
                            Name = "Django"
                        },
                        new
                        {
                            SkillId = 12,
                            Name = "Ruby on Rails"
                        },
                        new
                        {
                            SkillId = 13,
                            Name = "WordPress"
                        },
                        new
                        {
                            SkillId = 14,
                            Name = "HTML/CSS"
                        },
                        new
                        {
                            SkillId = 15,
                            Name = "Swift"
                        },
                        new
                        {
                            SkillId = 16,
                            Name = "Kotlin"
                        },
                        new
                        {
                            SkillId = 17,
                            Name = "Flutter"
                        },
                        new
                        {
                            SkillId = 18,
                            Name = "React Native"
                        },
                        new
                        {
                            SkillId = 19,
                            Name = "UI/UX Design"
                        },
                        new
                        {
                            SkillId = 20,
                            Name = "Figma"
                        },
                        new
                        {
                            SkillId = 21,
                            Name = "Adobe Photoshop"
                        },
                        new
                        {
                            SkillId = 22,
                            Name = "Adobe Illustrator"
                        },
                        new
                        {
                            SkillId = 23,
                            Name = "Graphic Design"
                        },
                        new
                        {
                            SkillId = 24,
                            Name = "Logo Design"
                        },
                        new
                        {
                            SkillId = 25,
                            Name = "Content Writing"
                        },
                        new
                        {
                            SkillId = 26,
                            Name = "Copywriting"
                        },
                        new
                        {
                            SkillId = 27,
                            Name = "Technical Writing"
                        },
                        new
                        {
                            SkillId = 28,
                            Name = "Translation"
                        },
                        new
                        {
                            SkillId = 29,
                            Name = "Editing & Proofreading"
                        },
                        new
                        {
                            SkillId = 30,
                            Name = "SEO"
                        },
                        new
                        {
                            SkillId = 31,
                            Name = "Social Media Marketing"
                        },
                        new
                        {
                            SkillId = 32,
                            Name = "Email Marketing"
                        },
                        new
                        {
                            SkillId = 33,
                            Name = "Google Ads"
                        },
                        new
                        {
                            SkillId = 34,
                            Name = "Data Analysis"
                        },
                        new
                        {
                            SkillId = 35,
                            Name = "SQL"
                        },
                        new
                        {
                            SkillId = 36,
                            Name = "Machine Learning"
                        },
                        new
                        {
                            SkillId = 37,
                            Name = "Power BI"
                        },
                        new
                        {
                            SkillId = 38,
                            Name = "Docker"
                        },
                        new
                        {
                            SkillId = 39,
                            Name = "Kubernetes"
                        },
                        new
                        {
                            SkillId = 40,
                            Name = "AWS"
                        },
                        new
                        {
                            SkillId = 41,
                            Name = "Azure"
                        },
                        new
                        {
                            SkillId = 42,
                            Name = "CI/CD"
                        },
                        new
                        {
                            SkillId = 43,
                            Name = "Project Management"
                        },
                        new
                        {
                            SkillId = 44,
                            Name = "Virtual Assistance"
                        },
                        new
                        {
                            SkillId = 45,
                            Name = "Bookkeeping"
                        },
                        new
                        {
                            SkillId = 46,
                            Name = "Video Editing"
                        },
                        new
                        {
                            SkillId = 47,
                            Name = "Voice Over"
                        },
                        new
                        {
                            SkillId = 48,
                            Name = "Motion Graphics"
                        });
                });

            modelBuilder.Entity("FreelanceHub.Domain.Models.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("tag_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TagId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("TagId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("tags", (string)null);

                    b.HasData(
                        new
                        {
                            TagId = 1,
                            Name = "C#"
                        },
                        new
                        {
                            TagId = 2,
                            Name = ".NET"
                        },
                        new
                        {
                            TagId = 3,
                            Name = "React"
                        },
                        new
                        {
                            TagId = 4,
                            Name = "SQL"
                        },
                        new
                        {
                            TagId = 5,
                            Name = "Figma"
                        },
                        new
                        {
                            TagId = 6,
                            Name = "SEO"
                        },
                        new
                        {
                            TagId = 7,
                            Name = "API"
                        },
                        new
                        {
                            TagId = 8,
                            Name = "Content Writing"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[normalized_name] IS NOT NULL");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Client",
                            NormalizedName = "CLIENT"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Freelancer",
                            NormalizedName = "FREELANCER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("user_tokens", (string)null);
                });

            modelBuilder.Entity("FreelanceHub.Domain.Models.Application", b =>
                {
                    b.HasOne("FreelanceHub.Domain.Models.ApplicationUser", "FreelancerUser")
                        .WithMany("Applications")
                        .HasForeignKey("FreelancerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FreelanceHub.Domain.Models.Job", "Job")
                        .WithMany("Applications")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FreelancerUser");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("FreelanceHub.Domain.Models.ApplicationAttachment", b =>
                {
                    b.HasOne("FreelanceHub.Domain.Models.Application", "Application")
                        .WithMany("ApplicationAttachments")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FreelanceHub.Domain.Models.Attachment", "Attachment")
                        .WithMany("ApplicationAttachments")
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Attachment");
                });

            modelBuilder.Entity("FreelanceHub.Domain.Models.ApplicationUser", b =>
                {
                    b.HasOne("FreelanceHub.Domain.Models.Attachment", "ProfileImageAttachment")
                        .WithMany()
                        .HasForeignKey("ProfileImageAttachmentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ProfileImageAttachment");
                });

            modelBuilder.Entity("FreelanceHub.Domain.Models.ApplicationUserRole", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FreelanceHub.Domain.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FreelanceHub.Domain.Models.Attachment", b =>
                {
                    b.HasOne("FreelanceHub.Domain.Models.ApplicationUser", "UploadedByUser")
                        .WithMany("UploadedAttachments")
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("FreelanceHub.Domain.Models.ClientProfile", b =>
                {
                    b.HasOne("FreelanceHub.Domain.Models.Attachment", "CompanyLogoAttachment")
                        .WithMany()
                        .HasForeignKey("CompanyLogoAttachmentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FreelanceHub.Domain.Models.ApplicationUser", "User")
                        .WithOne("ClientProfile")
                        .HasForeignKey("FreelanceHub.Domain.Models.ClientProfile", "UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CompanyLogoAttachment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FreelanceHub.Domain.Models.ClientProfileAttachment", b =>
                {
                    b.HasOne("FreelanceHub.Domain.Models.Attachment", "Attachment")
                        .WithMany("ClientProfileAttachments")
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FreelanceHub.Domain.Models.ClientProfile", "ClientProfile")
                        .WithMany("ClientProfileAttachments")
                        .HasForeignKey("ClientProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attachment");

                    b.Navigation("ClientProfile");
                });

            modelBuilder.Entity("FreelanceHub.Domain.Models.Contract", b =>
                {
                    b.HasOne("FreelanceHub.Domain.Models.Job", "Job")
                        .WithOne("Contract")
                        .HasForeignKey("FreelanceHub.Domain.Models.Contract", "JobId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FreelanceHub.Domain.Models.Application", "AcceptedApplication")
                        .WithOne("Contract")
                        .HasForeignKey("FreelanceHub.Domain.Models.Contract", "AcceptedApplicationId", "JobId")
                        .HasPrincipalKey("FreelanceHub.Domain.Models.Application", "ApplicationId", "JobId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AcceptedApplication");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("FreelanceHub.Domain.Models.ContractAttachment", b =>
                {
                    b.HasOne("FreelanceHub.Domain.Models.Attachment", "Attachment")
                        .WithMany("ContractAttachments")
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FreelanceHub.Domain.Models.Contract", "Contract")
                        .WithMany("ContractAttachments")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attachment");

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("FreelanceHub.Domain.Models.FreelancerProfile", b =>
                {
                    b.HasOne("FreelanceHub.Domain.Models.ApplicationUser", "User")
                        .WithOne("FreelancerProfile")
                        .HasForeignKey("FreelanceHub.Domain.Models.FreelancerProfile", "UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FreelanceHub.Domain.Models.FreelancerProfileAttachment", b =>
                {
                    b.HasOne("FreelanceHub.Domain.Models.Attachment", "Attachment")
                        .WithMany("FreelancerProfileAttachments")
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FreelanceHub.Domain.Models.FreelancerProfile", "FreelancerProfile")
                        .WithMany("FreelancerProfileAttachments")
                        .HasForeignKey("FreelancerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attachment");

                    b.Navigation("FreelancerProfile");
                });

            modelBuilder.Entity("FreelanceHub.Domain.Models.FreelancerSkill", b =>
                {
                    b.HasOne("FreelanceHub.Domain.Models.FreelancerProfile", "FreelancerProfile")
                        .WithMany("FreelancerSkills")
                        .HasForeignKey("FreelancerProfileId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FreelanceHub.Domain.Models.Skill", "Skill")
                        .WithMany("FreelancerSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("FreelancerProfile");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("FreelanceHub.Domain.Models.Job", b =>
                {
                    b.HasOne("FreelanceHub.Domain.Models.ApplicationUser", "ClientUser")
                        .WithMany("Jobs")
                        .HasForeignKey("ClientUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ClientUser");
                });

            modelBuilder.Entity("FreelanceHub.Domain.Models.JobAttachment", b =>
                {
                    b.HasOne("FreelanceHub.Domain.Models.Attachment", "Attachment")
                        .WithMany("JobAttachments")
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FreelanceHub.Domain.Models.Job", "Job")
                        .WithMany("JobAttachments")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attachment");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("FreelanceHub.Domain.Models.JobCategory", b =>
                {
                    b.HasOne("FreelanceHub.Domain.Models.Category", "Category")
                        .WithMany("JobCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FreelanceHub.Domain.Models.Job", "Job")
                        .WithMany("JobCategories")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("FreelanceHub.Domain.Models.JobSkill", b =>
                {
                    b.HasOne("FreelanceHub.Domain.Models.Job", "Job")
                        .WithMany("JobSkills")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FreelanceHub.Domain.Models.Skill", "Skill")
                        .WithMany("JobSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("FreelanceHub.Domain.Models.JobTag", b =>
                {
                    b.HasOne("FreelanceHub.Domain.Models.Job", "Job")
                        .WithMany("JobTags")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FreelanceHub.Domain.Models.Tag", "Tag")
                        .WithMany("JobTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("FreelanceHub.Domain.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("FreelanceHub.Domain.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("FreelanceHub.Domain.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FreelanceHub.Domain.Models.Application", b =>
                {
                    b.Navigation("ApplicationAttachments");

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("FreelanceHub.Domain.Models.ApplicationUser", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("ClientProfile");

                    b.Navigation("FreelancerProfile");

                    b.Navigation("Jobs");

                    b.Navigation("UploadedAttachments");
                });

            modelBuilder.Entity("FreelanceHub.Domain.Models.Attachment", b =>
                {
                    b.Navigation("ApplicationAttachments");

                    b.Navigation("ClientProfileAttachments");

                    b.Navigation("ContractAttachments");

                    b.Navigation("FreelancerProfileAttachments");

                    b.Navigation("JobAttachments");
                });

            modelBuilder.Entity("FreelanceHub.Domain.Models.Category", b =>
                {
                    b.Navigation("JobCategories");
                });

            modelBuilder.Entity("FreelanceHub.Domain.Models.ClientProfile", b =>
                {
                    b.Navigation("ClientProfileAttachments");
                });

            modelBuilder.Entity("FreelanceHub.Domain.Models.Contract", b =>
                {
                    b.Navigation("ContractAttachments");
                });

            modelBuilder.Entity("FreelanceHub.Domain.Models.FreelancerProfile", b =>
                {
                    b.Navigation("FreelancerProfileAttachments");

                    b.Navigation("FreelancerSkills");
                });

            modelBuilder.Entity("FreelanceHub.Domain.Models.Job", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("Contract");

                    b.Navigation("JobAttachments");

                    b.Navigation("JobCategories");

                    b.Navigation("JobSkills");

                    b.Navigation("JobTags");
                });

            modelBuilder.Entity("FreelanceHub.Domain.Models.Skill", b =>
                {
                    b.Navigation("FreelancerSkills");

                    b.Navigation("JobSkills");
                });

            modelBuilder.Entity("FreelanceHub.Domain.Models.Tag", b =>
                {
                    b.Navigation("JobTags");
                });
#pragma warning restore 612, 618
        }
    }
}
