// <auto-generated />
using System;
using FreelanceHub.Infrastructure.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FreelanceHub.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260718160859_SeededSkills")]
    partial class SeededSkills
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FreelanceHub.Domain.Models.ApplicationAttachment", b =>
                {
                    b.Property<int>("ApplicationId")
                        .HasColumnType("int")
                        .HasColumnName("application_id");

                    b.Property<int>("AttachmentId")
                        .HasColumnType("int")
                        .HasColumnName("attachment_id");

                    b.HasKey("ApplicationId", "AttachmentId");

                    b.HasIndex("AttachmentId");

                    b.ToTable("application_attachments", (string)null);
                });

            modelBuilder.Entity("FreelanceHub.Domain.Models.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("is_email_verified");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("last_name");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("normalized_username");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("username");

                    b.Property<int>("UserStatus")
                        .HasColumnType("int")
                        .HasColumnName("user_status");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("EmailIndex")
                        .HasFilter("[normalized_email] IS NOT NULL");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[normalized_username] IS NOT NULL");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("FreelanceHub.Domain.Models.ApplicationUserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("assigned_at")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("FreelanceHub.Domain.Models.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("attachment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("content_type");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("file_url");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("original_file_name");

                    b.Property<string>("StoredFileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("stored_file_name");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("uploaded_at")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<int>("UploadedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("uploaded_by_user_id");

                    b.HasKey("Id");

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("attachments", null, t =>
                        {
                            t.HasCheckConstraint("chk_attachments_file_size", "[file_size] IS NULL OR [file_size] >= 0");
                        });
                });

            modelBuilder.Entity("FreelanceHub.Domain.Models.ClientProfileAttachment", b =>
                {
                    b.Property<int>("ClientProfileId")
                        .HasColumnType("int")
                        .HasColumnName("client_profile_id");

                    b.Property<int>("AttachmentId")
                        .HasColumnType("int")
                        .HasColumnName("attachment_id");

                    b.Property<string>("AttachmentType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("attachment_type");

                    b.HasKey("ClientProfileId", "AttachmentId");

                    b.HasIndex("AttachmentId");

                    b.ToTable("client_profile_attachments", (string)null);
                });

            modelBuilder.Entity("FreelanceHub.Domain.Models.ContractAttachment", b =>
                {
                    b.Property<int>("ContractId")
                        .HasColumnType("int")
                        .HasColumnName("contract_id");

                    b.Property<int>("AttachmentId")
                        .HasColumnType("int")
                        .HasColumnName("attachment_id");

                    b.HasKey("ContractId", "AttachmentId");

                    b.HasIndex("AttachmentId");

                    b.ToTable("contract_attachments", (string)null);
                });

            modelBuilder.Entity("FreelanceHub.Domain.Models.FreelancerProfileAttachment", b =>
                {
                    b.Property<int>("FreelancerProfileId")
                        .HasColumnType("int")
                        .HasColumnName("freelancer_profile_id");

                    b.Property<int>("AttachmentId")
                        .HasColumnType("int")
                        .HasColumnName("attachment_id");

                    b.Property<string>("AttachmentDescription")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("attachment_description");

                    b.HasKey("FreelancerProfileId", "AttachmentId");

                    b.HasIndex("AttachmentId");

                    b.ToTable("freelancer_profile_attachments", (string)null);
                });

            modelBuilder.Entity("FreelanceHub.Domain.Models.FreelancerSkill", b =>
                {
                    b.Property<int>("FreelancerProfileId")
                        .HasColumnType("int")
                        .HasColumnName("freelancer_profile_id");

                    b.Property<int>("SkillId")
                        .HasColumnType("int")
                        .HasColumnName("skill_id");

                    b.HasKey("FreelancerProfileId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("freelancer_skills", (string)null);
                });

            modelBuilder.Entity("FreelanceHub.Domain.Models.JobAttachment", b =>
                {
                    b.Property<int>("JobId")
                        .HasColumnType("int")
                        .HasColumnName("job_id");

                    b.Property<int>("AttachmentId")
                        .HasColumnType("int")
                        .HasColumnName("attachment_id");

                    b.HasKey("JobId", "AttachmentId");

                    b.HasIndex("AttachmentId");

                    b.ToTable("job_attachments", (string)null);
                });

            modelBuilder.Entity("FreelanceHub.Domain.Models.JobSkill", b =>
                {
                    b.Property<int>("JobId")
                        .HasColumnType("int")
                        .HasColumnName("job_id");

                    b.Property<int>("SkillId")
                        .HasColumnType("int")
                        .HasColumnName("skill_id");

                    b.HasKey("JobId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("job_skills", (string)null);
                });

            modelBuilder.Entity("FreelanceHub.Domain.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("skill_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("skills", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "JavaScript"
                        },
                        new
                        {
                            Id = 2,
                            Name = "TypeScript"
                        },
                        new
                        {
                            Id = 3,
                            Name = "React"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Angular"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Vue.js"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Node.js"
                        },
                        new
                        {
                            Id = 7,
                            Name = "ASP.NET Core"
                        },
                        new
                        {
                            Id = 8,
                            Name = "PHP"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Laravel"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Python"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Django"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Ruby on Rails"
                        },
                        new
                        {
                            Id = 13,
                            Name = "WordPress"
                        },
                        new
                        {
                            Id = 14,
                            Name = "HTML/CSS"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Swift"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Kotlin"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Flutter"
                        },
                        new
                        {
                            Id = 18,
                            Name = "React Native"
                        },
                        new
                        {
                            Id = 19,
                            Name = "UI/UX Design"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Figma"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Adobe Photoshop"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Adobe Illustrator"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Graphic Design"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Logo Design"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Content Writing"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Copywriting"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Technical Writing"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Translation"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Editing & Proofreading"
                        },
                        new
                        {
                            Id = 30,
                            Name = "SEO"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Social Media Marketing"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Email Marketing"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Google Ads"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Data Analysis"
                        },
                        new
                        {
                            Id = 35,
                            Name = "SQL"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Machine Learning"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Power BI"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Docker"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Kubernetes"
                        },
                        new
                        {
                            Id = 40,
                            Name = "AWS"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Azure"
                        },
                        new
                        {
                            Id = 42,
                            Name = "CI/CD"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Project Management"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Virtual Assistance"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Bookkeeping"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Video Editing"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Voice Over"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Motion Graphics"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[normalized_name] IS NOT NULL");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Client",
                            NormalizedName = "CLIENT"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Freelancer",
                            NormalizedName = "FREELANCER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("user_tokens", (string)null);
                });

            modelBuilder.Entity("FreelanceHub.Domain.Models.ApplicationAttachment", b =>
                {
                    b.HasOne("FreelanceHub.Domain.Models.Attachment", "Attachment")
                        .WithMany("ApplicationAttachments")
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attachment");
                });

            modelBuilder.Entity("FreelanceHub.Domain.Models.ApplicationUserRole", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FreelanceHub.Domain.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FreelanceHub.Domain.Models.Attachment", b =>
                {
                    b.HasOne("FreelanceHub.Domain.Models.ApplicationUser", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("FreelanceHub.Domain.Models.ClientProfileAttachment", b =>
                {
                    b.HasOne("FreelanceHub.Domain.Models.Attachment", "Attachment")
                        .WithMany("ClientProfileAttachments")
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attachment");
                });

            modelBuilder.Entity("FreelanceHub.Domain.Models.ContractAttachment", b =>
                {
                    b.HasOne("FreelanceHub.Domain.Models.Attachment", "Attachment")
                        .WithMany("ContractAttachments")
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attachment");
                });

            modelBuilder.Entity("FreelanceHub.Domain.Models.FreelancerProfileAttachment", b =>
                {
                    b.HasOne("FreelanceHub.Domain.Models.Attachment", "Attachment")
                        .WithMany("FreelancerProfileAttachments")
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attachment");
                });

            modelBuilder.Entity("FreelanceHub.Domain.Models.FreelancerSkill", b =>
                {
                    b.HasOne("FreelanceHub.Domain.Models.Skill", "Skill")
                        .WithMany("FreelancerSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("FreelanceHub.Domain.Models.JobAttachment", b =>
                {
                    b.HasOne("FreelanceHub.Domain.Models.Attachment", "Attachment")
                        .WithMany("JobAttachments")
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attachment");
                });

            modelBuilder.Entity("FreelanceHub.Domain.Models.JobSkill", b =>
                {
                    b.HasOne("FreelanceHub.Domain.Models.Skill", "Skill")
                        .WithMany("JobSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("FreelanceHub.Domain.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("FreelanceHub.Domain.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("FreelanceHub.Domain.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FreelanceHub.Domain.Models.Attachment", b =>
                {
                    b.Navigation("ApplicationAttachments");

                    b.Navigation("ClientProfileAttachments");

                    b.Navigation("ContractAttachments");

                    b.Navigation("FreelancerProfileAttachments");

                    b.Navigation("JobAttachments");
                });

            modelBuilder.Entity("FreelanceHub.Domain.Models.Skill", b =>
                {
                    b.Navigation("FreelancerSkills");

                    b.Navigation("JobSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
